import { test, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';
test('feature console captures live actions, pauses, filters, exports and isolates navigation', async ({ page }) => {
 const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
 await page.goto('/simple-lock'); await expect(page.locator('.project-loading')).toHaveAttribute('aria-hidden', 'true');
 await page.getByLabel('Preimage (UTF-8, kept in memory)').fill('do-not-export-this-preimage');
 await page.getByRole('button', { name: 'Derive from preimage' }).click();
 await page.getByRole('button', { name: /Dev Console · Simple Lock Lab/ }).click();
 const panel = page.getByRole('region', { name: 'Simple Lock Lab developer console' });
 const entries = panel.locator('.dev-console-entry');
 await expect(panel).toBeVisible(); await expect(panel.getByRole('log')).toContainText('Derive lock');
 await expect(panel.getByRole('log')).toContainText('complete');
 const downloadEvent = page.waitForEvent('download'); await panel.getByRole('button', { name: 'Export JSONL' }).click();
 const download = await downloadEvent; const output = await readFile((await download.path())!, 'utf8');
 expect(output).toContain('Simple Lock Lab'); expect(output).not.toContain('do-not-export-this-preimage');
 await panel.getByRole('button', { name: 'Pause', exact: true }).click();
 const frozenCount = await entries.count();
 await page.getByRole('button', { name: 'Derive from preimage' }).click();
 await expect(panel).toContainText('Paused view'); expect(await entries.count()).toBe(frozenCount);
 await panel.getByRole('button', { name: 'Resume', exact: true }).click();
 await expect.poll(() => entries.count()).toBeGreaterThan(frozenCount);
 await panel.getByLabel('Filter', { exact: true }).fill('no-such-operation');
 await expect(entries).toHaveCount(0); await panel.getByLabel('Filter', { exact: true }).fill('');
 await panel.getByRole('button', { name: 'Clear', exact: true }).click(); await expect(entries).toHaveCount(0);
 await page.getByLabel('Preimage (UTF-8, kept in memory)').fill('');
 await page.getByRole('button', { name: 'Derive from preimage' }).click();
 await panel.getByLabel('Level', { exact: true }).selectOption('error');
 await expect(entries).toHaveCount(1); await expect(panel.getByRole('log')).toContainText('preimage');
 await panel.getByRole('button', { name: 'Collapse developer console' }).click();
 await page.getByRole('link', { name: 'Platform Overview', exact: true }).first().click();
 await page.getByRole('button', { name: /Dev Console · Platform Overview/ }).click();
 await expect(page.getByRole('region', { name: /developer console/ })).toHaveCount(1);
 await expect(page.getByRole('log')).not.toContainText('Derive lock');
 await page.goBack();
 await page.getByRole('button', { name: /Dev Console · Simple Lock Lab/ }).click();
 await expect(page.getByRole('log')).toContainText('Derive lock');
 await page.screenshot({ path: 'test-results/dev-console-desktop.png' });
 expect(errors).toEqual([]);
});
test('console fits a mobile viewport', async ({ page }) => {
 await page.setViewportSize({ width: 390, height: 844 }); await page.goto('/simple-lock'); await expect(page.locator('.project-loading')).toHaveAttribute('aria-hidden', 'true');
 await page.getByRole('button', { name: /Dev Console · Simple Lock Lab/ }).click();
 const panel = page.getByRole('region', { name: 'Simple Lock Lab developer console' });
 const box = (await panel.boundingBox())!;
 expect(box.x).toBeGreaterThanOrEqual(0); expect(box.x + box.width).toBeLessThanOrEqual(390); expect(box.y).toBeGreaterThanOrEqual(0);
 await expect(panel.getByRole('button', { name: 'Export JSONL' })).toBeInViewport();
 await page.screenshot({ path: 'test-results/dev-console-mobile.png' });
});
